name: build-prx

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Toolchain PSP complet (gcc/make) depuis GHCR
    container:
      image: ghcr.io/pspdev/pspdev:latest

    steps:
      - name: Checkout GePatch repo
        uses: actions/checkout@v4

      - name: Clone ARK-4 (SystemCtrl headers & lib)
        shell: sh
        run: |
          set -e
          git clone --depth 1 https://github.com/PSP-Archive/ARK-4.git
          export ARKROOT="$GITHUB_WORKSPACE/ARK-4"
          # Build SystemCtrlForKernel (stubs + lib kernel)
          make -C "$ARKROOT/libs/SystemCtrlForKernel"
          ls -l "$ARKROOT/libs/SystemCtrlForKernel" || true
          ls -l "$ARKROOT/common/include" || true

      - name: Build GePatch (PRX)
        shell: sh
        env:
          ARKROOT: ${{ github.workspace }}/ARK-4
        run: |
          set -e

          # ⚙️ Récupère les chemins PSPDEV/PSPSDK corrects dans ce conteneur
          PSPROOT="$(psp-config --pspdev-path)"     # ex: /usr/local/pspdev
          export PSPDEV="$PSPROOT"                  # Makefiles attendent $(PSPDEV)/psp/...
          export PATH="$PATH:$PSPDEV/bin"
          PSPSDK_DIR="$PSPDEV/psp/sdk"

          echo "PSPDEV=$PSPDEV"
          echo "PSPSDK_DIR=$PSPSDK_DIR"

          # Includes PSPSDK
          INC_PSPSDK_1="$PSPDEV/psp/include"
          INC_PSPSDK_2="$PSPDEV/psp/sdk/include"

          # Includes + lib pour SystemCtrl (ARK)
          INC_SYSCTRL_1="$ARKROOT/common/include"                       # contient systemctrl.h
          INC_SYSCTRL_2="$ARKROOT/libs/SystemCtrlForKernel/include"
          LIB_SYSCTRL="$ARKROOT/libs/SystemCtrlForKernel"

          echo "Using headers:"
          echo "  $INC_PSPSDK_1"
          echo "  $INC_PSPSDK_2"
          echo "  $INC_SYSCTRL_1"
          echo "  $INC_SYSCTRL_2"
          echo "Using libdir : $LIB_SYSCTRL"

          test -f Makefile || { echo "Makefile introuvable"; ls -la; exit 1; }

          make clean || true
          make \
            PSPSDK="$PSPSDK_DIR" \
            BUILD_PRX=1 \
            USE_KERNEL_LIBS=1 \
            USE_KERNEL_LIBC=1 \
            CFLAGS="$CFLAGS -I$INC_PSPSDK_1 -I$INC_PSPSDK_2 -I$INC_SYSCTRL_1 -I$INC_SYSCTRL_2" \
            CPPFLAGS="$CPPFLAGS -I$INC_PSPSDK_1 -I$INC_PSPSDK_2 -I$INC_SYSCTRL_1 -I$INC_SYSCTRL_2" \
            LDFLAGS="$LDFLAGS -L$LIB_SYSCTRL" \
            LIBS="$LIBS -lpspsystemctrl_kernel"

          echo "Fichiers générés :"
          find . -maxdepth 3 -type f \( -name "ge_patch.prx" -o -name "*.elf" -o -name "*.map" \) -print

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch_build
          path: |
            **/ge_patch.prx
            **/*.elf
            **/*.map
