name: build-prx

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Toolchain PSP complet avec make + psp-gcc
    container:
      image: ghcr.io/pspdev/pspdev:latest

    steps:
      - name: Checkout GePatch repo
        uses: actions/checkout@v4

      - name: Clone ARK-4 (SystemCtrl headers & lib)
        shell: sh
        run: |
          set -e
          git clone --depth 1 https://github.com/PSP-Archive/ARK-4.git

      - name: Build SystemCtrlForKernel (with ARKROOT)
        shell: sh
        run: |
          set -e
          export ARKROOT="$GITHUB_WORKSPACE/ARK-4"
          echo "ARKROOT=$ARKROOT"
          make -C "$ARKROOT/libs/SystemCtrlForKernel"
          ls -l "$ARKROOT/libs/SystemCtrlForKernel"

      - name: Show toolchain
        shell: sh
        run: |
          set -e
          which make || true
          which psp-gcc || true
          psp-gcc --version || true
          echo "Repo tree:"; ls -la

      - name: Build GePatch (PRX) linking SystemCtrl
        shell: sh
        env:
          ARKROOT: ${{ github.workspace }}/ARK-4
        run: |
          set -e
          test -f Makefile || { echo "Makefile introuvable"; ls -la; exit 1; }

          INC_SYSCTRL="$ARKROOT/libs/SystemCtrlForKernel/include"
          LIB_SYSCTRL="$ARKROOT/libs/SystemCtrlForKernel"
          echo "Using headers: $INC_SYSCTRL"
          echo "Using libdir : $LIB_SYSCTRL"

          make clean || true
          make \
            BUILD_PRX=1 \
            USE_KERNEL_LIBS=1 \
            USE_KERNEL_LIBC=1 \
            CFLAGS="$CFLAGS -I$INC_SYSCTRL" \
            CPPFLAGS="$CPPFLAGS -I$INC_SYSCTRL" \
            LDFLAGS="$LDFLAGS -L$LIB_SYSCTRL" \
            LIBS="$LIBS -lpspsystemctrl_kernel"

          echo "Fichiers générés :"
          find . -maxdepth 2 -type f \( -name "ge_patch.prx" -o -name "*.elf" -o -name "*.map" \) -print

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch_build
          path: |
            **/ge_patch.prx
            **/*.elf
            **/*.map
