name: build-prx

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/pspdev/pspdev:latest

    steps:
      - name: Checkout GePatch repo
        uses: actions/checkout@v4

      - name: Clone ARK-4 (SystemCtrl headers & lib)
        shell: sh
        run: |
          set -e
          git clone --depth 1 https://github.com/PSP-Archive/ARK-4.git

      - name: Build SystemCtrlForKernel (export ARKROOT)
        shell: sh
        run: |
          set -e
          export ARKROOT="$GITHUB_WORKSPACE/ARK-4"
          echo "ARKROOT=$ARKROOT"
          make -C "$ARKROOT/libs/SystemCtrlForKernel"
          ls -l "$ARKROOT/libs/SystemCtrlForKernel"

      - name: Build GePatch (PRX) linking SystemCtrl + PSPSDK includes
        shell: sh
        env:
          ARKROOT: ${{ github.workspace }}/ARK-4
        run: |
          set -e

          # Récupère la racine du toolchain PSP (PSPDEV) depuis le conteneur
          export PSPDEV="$(psp-config --psp-prefix)"
          export PATH="$PATH:$PSPDEV/bin"
          echo "PSPDEV=$PSPDEV"
          test -n "$PSPDEV" || { echo "PSPDEV introuvable"; exit 1; }

          test -f Makefile || { echo "Makefile introuvable"; ls -la; exit 1; }

          INC_SYSCTRL="$ARKROOT/libs/SystemCtrlForKernel/include"
          LIB_SYSCTRL="$ARKROOT/libs/SystemCtrlForKernel"

          # Includes PSPSDK
          INC_PSPSDK_1="$PSPDEV/psp/include"
          INC_PSPSDK_2="$PSPDEV/psp/sdk/include"

          echo "Using headers:"
          echo "  $INC_PSPSDK_1"
          echo "  $INC_PSPSDK_2"
          echo "  $INC_SYSCTRL"
          echo "Using libdir : $LIB_SYSCTRL"

          make clean || true

          make \
            BUILD_PRX=1 \
            USE_KERNEL_LIBS=1 \
            USE_KERNEL_LIBC=1 \
            CFLAGS="$CFLAGS -I$INC_PSPSDK_1 -I$INC_PSPSDK_2 -I$INC_SYSCTRL" \
            CPPFLAGS="$CPPFLAGS -I$INC_PSPSDK_1 -I$INC_PSPSDK_2 -I$INC_SYSCTRL" \
            LDFLAGS="$LDFLAGS -L$LIB_SYSCTRL" \
            LIBS="$LIBS -lpspsystemctrl_kernel"

          echo "Fichiers générés :"
          find . -maxdepth 2 -type f \( -name "ge_patch.prx" -o -name "*.elf" -o -name "*.map" \) -print

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch_build
          path: |
            **/ge_patch.prx
            **/*.elf
            **/*.map
