name: build-prx

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # 👉 Utilise l'image "pspdev" (avec outils de build) plutôt que "psptoolchain"
    container:
      image: ghcr.io/pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # IMPORTANT: /bin/sh (pas bash)
      - name: Show env
        shell: sh
        run: |
          set -e
          echo "Shell: $SHELL"
          echo "PATH=$PATH"
          which make || true
          which psp-gcc || true
          psp-gcc --version || true
          echo "Repo tree:"; ls -la

      - name: Build GePatch (PRX)
        shell: sh
        run: |
          set -e
          # ➜ Ton Makefile est à la racine du repo (d'après ton log)
          if [ -f Makefile ]; then
            echo "Using Makefile in $(pwd)"
          else
            echo "Makefile introuvable. Contenu:"; ls -la; exit 1
          fi

          make clean || true
          make

          echo "Fichiers générés :"
          ls -l || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch_build
          path: |
            **/ge_patch.prx
            **/*.elf
            **/*.map
