name: build-prx

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # fetch ARK-4 too

      - name: Install OS dependencies (Ubuntu 24.04)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential cmake python3 zip \
            pkgconf libreadline8 libusb-0.1-4 \
            libgpgme11t64 libgpgme-dev \
            libarchive-tools fakeroot curl ca-certificates

      - name: Install PSP toolchain
        run: |
          git clone https://github.com/pspdev/pspdev.git
          cd pspdev
          # méthode canonique documentée
          ./bootstrap.sh
          ./depends/check-dependencies.sh
          ./toolchain.sh
          # exposer PSPDEV/PSP binaires à la suite des jobs
          echo "PSPDEV=/usr/local/pspdev" >> $GITHUB_ENV
          echo "/usr/local/pspdev/bin" >> $GITHUB_PATH

      - name: Add ARK-4 submodule (if not present)
        run: |
          if [ ! -d "ARK-4" ]; then
            git submodule add https://github.com/PSP-Archive/ARK-4.git ARK-4 || true
          fi

      - name: Build
        run: |
          make

      - name: Upload PRX artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch.prx
          path: ge_patch.prx
