name: build-prx

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Image du toolchain PSP (hébergée sur GHCR)
    container:
      image: ghcr.io/pspdev/psptoolchain:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # IMPORTANT: utiliser /bin/sh (pas bash)
      - name: Build GePatch (PRX)
        shell: sh
        run: |
          set -e
          echo "PWD = $(pwd)"
          echo "Contenu racine:"
          ls -la

          # 👉 ADAPTE le chemin si besoin (où se trouve ton Makefile)
          if [ -d GePatch-0.2/GePatch-0.2 ]; then
            cd GePatch-0.2/GePatch-0.2
          elif [ -f Makefile ]; then
            :
          else
            echo "Makefile introuvable; arborescence:" >&2
            find . -maxdepth 3 -type f -name Makefile -print
            exit 1
          fi

          echo "Dossier build = $(pwd)"
          ls -la

          make clean || true
          make

          echo "Fichiers générés :"
          ls -l || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ge_patch_build
          path: |
            **/ge_patch.prx
            **/*.elf
            **/*.map
