name: setup-libarchive-shim

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-setup:
    name: make setup-libarchive-shim (pspdev container)
    runs-on: ubuntu-latest

    # Utilise une image qui contient déjà le PSP SDK dans /usr/local/pspdev
    container:
      image: ghcr.io/pspdev/pspdev:latest
      # si besoin d'un shell login pour PATH/PSPDEV, on peut ajouter:
      # options: --entrypoint /bin/bash

    env:
      PSPDEV: /usr/local/pspdev
      PATH: /usr/local/pspdev/bin:/usr/local/pspdev/psp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      # (Optionnel) Dépendances côté host/container
      # Ajoute ce dont ton Makefile a besoin en plus du SDK PSP
      - name: Install extra build deps
        run: |
          apt-get update
          apt-get install -y build-essential pkg-config libarchive-dev git ca-certificates

      - name: Run make target
        run: |
          make setup-libarchive-shim
